services:
  sql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.0
    container_name: astro_sql_proxy
    command:
      - "--address=0.0.0.0"
      - "--port=5432"
      - "airflowtest-475719:us-east1:airflow-metadata"
      - "--credentials-file=/secrets/key.json"
    volumes:
      - ./secrets/cloud-sql-proxy-service-account.json:/secrets/key.json:ro
    ports:
      - "5434:5432"
    restart: unless-stopped
